---
- name: Role sanity check
  assert:
    that:
      - echolink_config != {} or not echolink

- name: Install packages
  block:
    - name: Install apt key
      get_url:
        url: https://raw.githubusercontent.com/AI5A/asl-pkgs/main/pkg_pub_key.asc
        dest: /etc/apt/trusted.gpg.d/asl.asc
        checksum: sha256:1530eec11a412b65873c410d5886b20910a8c817ee34f48ca8dcba7acacf04ad

    - name: Set up apt repository
      apt_repository:
        repo: deb [signed-by=/etc/apt/trusted.gpg.d/asl.asc] https://d2hsfuechl7w22.cloudfront.net/deb/{{ ansible_distribution_release }} {{ ansible_distribution_release }} bullseye main
        filename: asl

    - name: Install kernel headers
      apt:
        name:
          - "{{ 'linux-headers' if 'arm' in ansible_architecture else 'linux-headers-generic' }}"

    - name: Install packages
      apt:
        update_cache: true
        name:
          - asl-asterisk
          - asl-dahdi
          - allstar-helpers
          - asl-update-node-list
      register: install

    - name: Modprobe dahdi
      command:
        cmd: modprobe dahdi
        creates: /dev/dahdi/pseudo
      when: install is defined and install is changed

    - name: Remove boilerplate files if fresh install
      file:
        dest: "{{ config_directory }}"
        state: absent
      when: install is defined and install is changed
  when: install_method != 'config-only'

- name: Create node-specific directories for configs
  file:
    dest: "{{ config_directory }}/{{ item }}"
    owner: asterisk
    group: asterisk
    mode: 0755
    state: directory
  with_items:
    - extensions
    - rpt
    - simpleusb

- name: Copy configuration file templates
  template:
    src: "{{ item }}"
    dest: "{{ config_directory }}/{{ item }}"
    owner: asterisk
    group: asterisk
    mode: 0644
  with_items:
    - extensions.conf
    - iax.conf
    - manager.conf
    - rpt.conf
    - simpleusb.conf
    - modules.conf
  notify:
    - reload asterisk

- name: Copy echolink configuration file
  template:
    src: echolink.conf
    dest: "{{ config_directory }}/echolink.conf"
    owner: asterisk
    group: asterisk
    mode: 0644
  when: echolink
  notify:
    - reload asterisk

- name: Copy static configuration files
  copy:
    src: "{{ item }}"
    dest: "{{ config_directory }}/{{ item }}"
    owner: asterisk
    group: asterisk
    mode: 0644
  with_items:
    - asterisk.conf
    - codecs.conf
    - dnsmgr.conf
    - enum.conf
    - features.conf
    - indications.conf
    - logger.conf
  notify:
    - reload asterisk

- name: Generate node-specific config files for including elsewhere
  template:
    src: "node_includes/{{ item.src }}"
    dest: "{{ config_directory }}/{{ item.subdir }}/{{ node_number }}-{{ item.end }}.conf"
    owner: asterisk
    group: asterisk
    mode: 0644
  with_items:
    - { subdir: extensions, src: radio-secure.conf, end: radio-secure }
    - { subdir: extensions, src: iaxrpt.conf, end: iaxrpt }
    - { subdir: extensions, src: iax-client.conf, end: iax-client }
    - { subdir: rpt, src: rpt.conf, end: rpt }
    - { subdir: rpt, src: node.conf, end: node }
    - { subdir: simpleusb, src: simpleusb.conf, end: simpleusb }
  notify:
    - reload asterisk

- name: Ensure empty chan_dahdi.conf file exists
  file:
    dest: "{{ config_directory }}/chan_dahdi.conf"
    owner: asterisk
    group: asterisk
    mode: 0644
    state: touch
    modification_time: preserve
    access_time: preserve
  notify:
    - reload asterisk

- name: Set up services
  service:
    enabled: true
    state: started
    name: "{{ item }}"
  with_items:
    - asl-asterisk
    - asl-update-node-list
  when:
    - install_method != 'config-only'

#- name: firewall - allow AllStarLink
#  community.general.ufw:
#    rule: allow
#    port: "{{ port }}"
#    comment: AllStarLink port

- name: Work around upstream busted logrotate config
  copy:
    src: logrotate.conf
    dest: /etc/logrotate.d/asl-asterisk
    owner: root
    group: root
    mode: 0644
