argument_specs:
  main:
    short_description: Set up an AllStarLink node
    author:
      - Rick Elrod
    options:
      install_method:
        type: str
        required: false
        default: ai5a-deb
        choices:
          - ai5a-deb
          - upstream-deb
          - config-only
        description: |
          How should ASL be installed?
          ai5a-deb: Uses the AI5A fork of AllStarLink
          upstream-deb: Uses the upstream AllStarLink (often does not support
                        newer Debian)
          config-only: Writes out templated config files but does not install
                       packages (useful for Docker installations to mount, etc.)

      config_directory:
        type: str
        required: false
        default: /etc/asterisk
        description: |
          Where should we write out the config files to?
          This directory will be *deleted* on initial install (unless
          install_method is config-only). Generally you should not change this
          unless you are using install_method: config-only and want to mount
          this directory from elsewhere.

      node_number:
        type: int
        required: true
        description: The node number we're configuring.

      carrierfrom:
        type: str
        required: false
        default: usb
        description: "https://wiki.allstarlink.org/wiki/SimpleUSB_Channel_Driver"

      duplex:
        type: int
        required: false
        default: 1
        description: "https://wiki.allstarlink.org/wiki/Rpt.conf#duplex.3D"

      idrecording:
        type: str
        required: true
        description: "https://wiki.allstarlink.org/wiki/Rpt.conf#idrecording.3D"

      idtalkover:
        type: str
        required: true
        description: "https://wiki.allstarlink.org/wiki/Rpt.conf#idtalkover.3D"

      bind:
        type: str
        required: false
        default: 0.0.0.0
        description: IP address/interface to bind to.

      port:
        type: int
        required: false
        default: 4569
        description: Port number to bind to.

      reg_password:
        type: str
        required: true
        description: Password to register with the AllStarLink server.

      reg_server:
        type: str
        required: false
        default: register.allstarlink.org
        description: AllStarLink registration server hostname.

      tailmessagelist:
        type: list
        elements: str
        required: false
        description: >-
          List of messages to include in the tail of a transmission every once
          in a while.

      tailmessagetime:
        type: int
        required: false
        default: 3600000
        description: How often tail messages should play, if enabled.

      delinked_courtesy_tone:
        type: str
        required: false
        default: "|t(750,0,125,2048)(1000,0,80,2048)"
        description: Courtesy tone when node is not linked to anything.

      link_rx_courtesy_tone:
        type: str
        required: false
        default: "|t(800,0,40,1500)(0,0,30,0)(800,0,40,1500)"
        description: Courtesy tone when node a linked remote unkeys.

      linked_courtesy_tone:
        type: str
        required: false
        default: "|t(660,0,50,2048)"
        description: Courtesy tone when someone on RF unkeys but we are linked.

      unkeywait:
        type: int
        required: false
        default: 800
        description: How long to wait before sending courtesy tones, etc.

      totime:
        type: int
        required: false
        default: 600000
        description: How long until we time out? Defaults to 10 minutes.

      outstreamcmd:
        type: str
        required: false
        default: null
        description: A command to call for streaming audio from the node.

      macros:
        type: list
        elements: dict
        required: false
        default: []
        description: >-
          A list of dictionaries with keys:
          - comment (optional, string),
          - macro (int),
          - command (string)

      scheduler:
        type: list
        elements: dict
        required: false
        default: []
        description: |
          A list of dictionaries with keys:
          - comment (optional, string),
          - macro (int),
          - when (cron style time format)
          - finish (optional, cron style time format)
          - finish_macro (optional, int)

      rxchannel:
        type: str
        required: false
        default: SimpleUSB/usb_{{ node_number }}
        description: The radio interface to use.

      echolink:
        type: bool
        required: false
        default: false
        description: Should echolink be enabled and loaded?

      echolink_config:
        type: dict
        required: false
        default: {}
        description: >-
          Required when 'echolink' is true.
          A dictionary of echolink configuration options. See
          https://wiki.allstarlink.org/wiki/Echolink.conf_-_Echolink_Channel_Driver
          for more information. We directly translate the keys in this dictionary
          to the echolink.conf file. The following keys are hardcoded:
          astnode, context, server1, server2, server3, rtcptimeout, recfile

      erxgain:
        type: int
        required: false
        default: -3
        description: >-
          https://wiki.allstarlink.org/wiki/Rpt.conf#erxgain.3D
          Receive gain for echolink in db-volts.

      etxgain:
        type: int
        required: false
        default: 3
        description: >-
          https://wiki.allstarlink.org/wiki/Rpt.conf#etxgain.3D
          Transmit gain for echolink in db-volts.

      eannmode:
        type: int
        required: false
        default: 1
        description: |
          https://wiki.allstarlink.org/wiki/Rpt.conf#eannmode.3D
          Announce mode for echolink.
          1 = Say only node number on echolink connects
          2 = Say phonetic call sign only on echolink connects
          3 = Say phonetic call sign and node number on echolink connects

      acl_context:
        type: str
        required: false
        default: whitelist
        choices:
          - whitelist
          - blacklist
        description: Whether the node should whitelist, or blacklist, incoming connections.

      ami:
        type: bool
        required: false
        default: false
        description: Should the Asterisk Manager Interface be enabled?

      ami_port:
        type: int
        required: false
        default: 5038
        description: Port to bind the AMI to.

      ami_bindaddr:
        type: str
        required: false
        default: 127.0.0.1
        description: IP address to bind the AMI to.

      ami_users:
        type: dict
        required: false
        default: {}
        description: >-
          A dictionary of AMI users to create. The keys are the usernames, and
          the values are dictionaries that get translated directly to the
          configuration file.

      local_nodes:
        type: list
        elements: dict
        required: false
        default: []
        description: |
          A list of local nodes, not including the current node and only
          including nodes not already covered by the asterisk external nodes
          update script. This is for nodes, for example, that are on your LAN
          and you want to connect to directly without hairpinning.
          Each dict must include: node_number, ip, port

      startup_macro:
        type: list
        elements: str
        required: false
        default: []
        description: >-
          The macro to run on startup. This is useful for things like connecting
          to a hub, etc. This is a list of strings (mainly so that you can
          comment what each macro does in your playbook).

      hangtime:
        type: int
        required: false
        default: 500
        description: >-
          Repeater hang time in ms.
          https://wiki.allstarlink.org/wiki/Rpt.conf#hangtime.3D

      althangtime:
        type: int
        required: false
        default: 1000
        description: >-
          Alternate hang time in ms.
          https://wiki.allstarlink.org/wiki/Rpt.conf#althangtime.3D

      holdofftelem:
        type: bool
        required: false
        default: false
        description: >-
          Forces all telemetry to be held off until a local user on the receiver
          or a remote user over a link unkeys. See
          https://wiki.allstarlink.org/wiki/Rpt.conf#holdofftelem.3D

      nounkeyct:
        type: bool
        required: false
        default: false
        description: >-
          If true, the courtesy tone will not be sent when a user unkeys.
          https://wiki.allstarlink.org/wiki/Rpt.conf#nounkeyct.3D

      telemdynamic:
        type: bool
        required: false
        default: true
        description: >-
          If true, telemetry can be dynamically enabled and disabled by the
          COP commands. See
          https://wiki.allstarlink.org/wiki/Rpt.conf#telemdynamic.3D

      telemdefault:
        type: int
        required: false
        default: 2
        description: |
          0 = telemetry output off
          1 = telemetry output on
          2 = timed telemetry output on command execution and for a short time thereafter.
          https://wiki.allstarlink.org/wiki/Rpt.conf#telemdefault.3D

      politeid:
        type: int
        required: false
        default: 30000
